contact_links:
  - name: Feature Request
    url: https://github.com/WSL0809/Authenticator/discussions/new
    about: Please request features here.
  - name: Translation Issues
    url: https://github.com/WSL0809/Authenticator/issues
    about: Please report translation issues here.
